export const SEED_CLANS = [
  {
    id: "steel-meridian-vanguard",
    name: "Steel Meridian Vanguard",
    tag: "SMVG",
    image: "/images/clans/smvg.svg",
    platform: "PC",
    tier: "Moon",
    members: 742,
    mrRequired: 15,
    playstyles: ["Hardcore", "Steel Path", "Endgame"],
    region: "North America",
    language: "English",
    status: "Selective",
    leader: "CressaTal",
    discord: "https://discord.gg/warframe",
    founded: "2018",
    allianceId: "solar-rail",
    headline: "Coordinated endgame. No passengers.",
    summary: "Veteran Moon clan for players who want scheduled clears, not an empty research lab.",
    about:
      "We run scheduled Steel Path sorties, archon hunts, and long survival sessions. Research is complete. Leadership is on daily. Show up prepared and communicate.",
    offering: [
      "Fully researched Moon clan",
      "Scheduled Steel Path and hunt nights",
      "Mentors for high-MR players new to squad roles",
      "Active trade and relic channels",
    ],
    requirements: [
      "MR 15 minimum",
      "Mic for scheduled runs",
      "Join Discord within 48 hours",
      "No AFK farming under the tag",
    ],
    featured: true,
    createdAt: "2026-08-12T16:00:00.000Z",
  },
  {
    id: "lotus-garden",
    name: "Lotus Garden",
    tag: "LTGD",
    image: "/images/clans/ltgd.svg",
    platform: "PlayStation",
    tier: "Storm",
    members: 64,
    mrRequired: 2,
    playstyles: ["Casual", "New Player Friendly", "Social"],
    region: "Europe",
    language: "English",
    status: "Open",
    leader: "SarynBloom",
    discord: "https://discord.gg/warframe",
    founded: "2022",
    allianceId: "quiet-hours",
    headline: "Low pressure. Actual people.",
    summary: "A casual clan for story players, fashion, and anyone still finding their first prime.",
    about:
      "Lotus Garden exists because a lot of players bounce off the early star chart alone. We help with junctions, quests, and first builds. Voice is optional. Kindness is not.",
    offering: [
      "Patient veterans most evenings (CET)",
      "Starter frame and weapon help",
      "Fashion nights",
      "No attendance requirements",
    ],
    requirements: ["MR 2+", "Be respectful in Discord", "Ask before taking limited clan resources"],
    featured: true,
    createdAt: "2026-08-20T11:30:00.000Z",
  },
  {
    id: "void-walkers",
    name: "Void Walkers",
    tag: "VOID",
    image: "/images/clans/void.svg",
    platform: "PC",
    tier: "Mountain",
    members: 218,
    mrRequired: 12,
    playstyles: ["Endgame", "Steel Path", "Railjack"],
    region: "Global",
    language: "English",
    status: "Open",
    leader: "RellEcho",
    discord: "https://discord.gg/warframe",
    founded: "2019",
    allianceId: "solar-rail",
    headline: "Hunts, vaults, and crews that show up.",
    summary: "Focus on Eidolons, isolation vaults, and late-game resource loops.",
    about:
      "Mountain clan with a serious hunting wing and a relaxed social wing. LFG rooms actually get used. If you want consistent tricap groups or a crew for deep archimedea, start here.",
    offering: [
      "Nightly hunt and vault groups",
      "Railjack mentors",
      "Shared relic and focus calendar",
      "Complete research including Railjack",
    ],
    requirements: ["MR 12+", "At least one viable Steel Path frame", "Discord required"],
    featured: true,
    createdAt: "2026-08-28T19:15:00.000Z",
  },
  {
    id: "cetus-collective",
    name: "Cetus Collective",
    tag: "CETC",
    image: "/images/clans/cetc.svg",
    platform: "Xbox",
    tier: "Shadow",
    members: 21,
    mrRequired: 0,
    playstyles: ["New Player Friendly", "Casual", "Nightwave"],
    region: "North America",
    language: "English",
    status: "Open",
    leader: "OstronTea",
    discord: "https://discord.gg/warframe",
    founded: "2025",
    allianceId: "quiet-hours",
    headline: "Small Xbox clan for new and returning players.",
    summary: "We keep the roster small on purpose. You will know everyone.",
    about:
      "We walk people through the first planets and basic foundry mistakes. No tryhard culture.",
    offering: ["One-on-one star chart help", "Shared Nightwave tracking", "No drama"],
    requirements: ["Any MR", "Be patient with other new players"],
    featured: false,
    createdAt: "2026-09-01T08:00:00.000Z",
  },
  {
    id: "orokin-restoration",
    name: "Orokin Restoration",
    tag: "GOLD",
    image: "/images/clans/gold.svg",
    platform: "PC",
    tier: "Storm",
    members: 88,
    mrRequired: 8,
    playstyles: ["Fashion Frame", "Social", "Trading"],
    region: "Europe",
    language: "English",
    status: "Selective",
    leader: "PaletteLead",
    discord: "https://discord.gg/warframe",
    founded: "2021",
    allianceId: "northern-command",
    headline: "Looks first. Then we farm.",
    summary: "Fashion-first clan with a complete lab and a clean trade floor.",
    about: "Color-palette nights, captura sessions, and a ruthless Baro shopping list.",
    offering: ["Captura rooms", "Baro and trade alerts", "Full pigment research"],
    requirements: ["MR 8+", "Share one fashion loadout in Discord", "No marketplace scams"],
    featured: false,
    createdAt: "2026-07-30T14:00:00.000Z",
  },
  {
    id: "dry-dock-irregulars",
    name: "Dry Dock Irregulars",
    tag: "DDI",
    image: "/images/clans/ddi.svg",
    platform: "PlayStation",
    tier: "Mountain",
    members: 156,
    mrRequired: 10,
    playstyles: ["Railjack", "Endgame", "Casual"],
    region: "North America",
    language: "English",
    status: "Open",
    leader: "CephalonPilot",
    discord: "https://discord.gg/warframe",
    founded: "2020",
    allianceId: "northern-command",
    headline: "Your Railjack crew is already here.",
    summary: "Railjack-first clan that still runs regular planet content and weekly hunts.",
    about: "Intrinsics mentors, storm-season events, and a dry dock that is actually used.",
    offering: ["Crewed Railjack nights 4x a week", "Avionic advice", "Complete research"],
    requirements: ["MR 10+", "Own a Railjack or be ready to build one"],
    featured: false,
    createdAt: "2026-08-05T21:00:00.000Z",
  },
  {
    id: "nightwave-scribes",
    name: "Nightwave Scribes",
    tag: "NWS",
    image: "/images/clans/nws.svg",
    platform: "Nintendo Switch",
    tier: "Ghost",
    members: 8,
    mrRequired: 5,
    playstyles: ["Nightwave", "Casual", "Social"],
    region: "Oceania",
    language: "English",
    status: "Open",
    leader: "NoraNightOwl",
    discord: "https://discord.gg/warframe",
    founded: "2024",
    allianceId: "quiet-hours",
    headline: "Weekly acts. No lectures.",
    summary: "Small Switch clan that finishes the Nightwave season together.",
    about: "We ping acts, share efficient nodes, and never shame a handheld connection.",
    offering: ["Act tracking channel", "Low-commitment weekly voice"],
    requirements: ["MR 5+", "Play at least some Nightwave"],
    featured: false,
    createdAt: "2026-08-18T04:20:00.000Z",
  },
  {
    id: "sanguine-court",
    name: "Sanguine Court",
    tag: "SNCT",
    image: "/images/clans/snct.svg",
    platform: "PC",
    tier: "Shadow",
    members: 27,
    mrRequired: 18,
    playstyles: ["Hardcore", "Steel Path", "Endgame"],
    region: "Europe",
    language: "English",
    status: "Trial Required",
    leader: "KuvaQueen",
    discord: "https://discord.gg/warframe",
    founded: "2023",
    allianceId: "solar-rail",
    headline: "Trial week. Then the roster decides.",
    summary: "Small elite clan for players who already have the builds.",
    about: "One-week trial: a Steel Path run, a hunt, and a social check. Tight roster on purpose.",
    offering: ["High-signal LFG", "Loadout reviews", "Alliance research access"],
    requirements: ["MR 18+", "Complete a one-week trial", "Mature communication"],
    featured: false,
    createdAt: "2026-08-25T17:45:00.000Z",
  },
];

export const SEED_ALLIANCES = [
  {
    id: "solar-rail",
    name: "Solar Rail",
    tag: "RAIL",
    image: "/images/alliances/rail.svg",
    platforms: ["PC"],
    region: "Global",
    language: "English",
    status: "Selective",
    clanCount: 12,
    members: 1840,
    discord: "https://discord.gg/warframe",
    headline: "Endgame clans that share a calendar.",
    summary: "A PC alliance for Steel Path, hunts, and clans that actually talk to each other.",
    about:
      "Solar Rail is a group of established clans with a shared Discord and weekly event board. Member clans keep their own culture. The alliance exists so you never farm the hard stuff alone.",
    offering: [
      "Shared hunt and raid-style event calendar",
      "Cross-clan LFG",
      "Research overflow between member clans",
    ],
    requirements: [
      "Clan must have an active Discord",
      "Leadership available weekly",
      "No ghost clans",
    ],
    featured: true,
    createdAt: "2026-08-10T12:00:00.000Z",
  },
  {
    id: "quiet-hours",
    name: "Quiet Hours",
    tag: "QHRS",
    image: "/images/alliances/qhrs.svg",
    platforms: ["PlayStation", "Xbox", "Nintendo Switch"],
    region: "Global",
    language: "English",
    status: "Open",
    clanCount: 9,
    members: 410,
    discord: "https://discord.gg/warframe",
    headline: "Console-friendly. New players welcome.",
    summary: "An alliance of smaller clans that care more about people than clear times.",
    about:
      "Quiet Hours groups casual and new-player clans so nobody is stuck in a 6-person dead roster. Cross-play friends can still sit in the same alliance Discord.",
    offering: ["Shared beginner guides", "Cross-clan social events", "No attendance drama"],
    requirements: ["Be decent to new players", "Keep recruiting posts honest"],
    featured: true,
    createdAt: "2026-08-16T09:00:00.000Z",
  },
  {
    id: "northern-command",
    name: "Northern Command",
    tag: "NCMD",
    image: "/images/alliances/ncmd.svg",
    platforms: ["PC", "PlayStation"],
    region: "North America",
    language: "English",
    status: "Open",
    clanCount: 6,
    members: 620,
    discord: "https://discord.gg/warframe",
    headline: "NA evenings. Trade, Railjack, fashion.",
    summary: "A practical NA alliance for clans that play after work.",
    about: "We overlap peak hours on purpose. Trade boards stay clean. Railjack crews get filled.",
    offering: ["NA peak-hour coverage", "Shared dry dock nights", "Moderated trade board"],
    requirements: ["Primary region NA", "Active leadership"],
    featured: false,
    createdAt: "2026-07-22T18:00:00.000Z",
  },
];
